const Robots=[
    {
        name:"ram",
        email:"ram@gmail.com",
        id:1
    },
    {
        name:"shriram",
        email:"shriram@gmail.com",
        id:2
    },
    {
        name:"aman",
        email:"aman@gmail.com",
        id:3
    },
    {
        name:"raju",
        email:"raju@gmail.com",
        id:4
    },
    {
        name:"pankaj",
        email:"pankaj@gmail.com",
        id:5
    },
    {
        name:"sodi",
        email:"sodi@gmail.com",
        id:6
    },
    {
        name:"shakhsi",
        email:"shakkshi@gmail.com",
        id:7
    },
    {
        name:"baby",
        email:"baby@gmail.com",
        id:9
    },
    {
        name:"chandni",
        email:"ch@gmail.com",
        id:10
    },
    {
        name:"manish",
        email:"ms@gmail.com",
        id:11
    },
    {
        name:"arun",
        email:"arun@gmail.com",
        id:12
    },
    {
        name:"vivek rajput",
        email:"vivek@gmail.com",
        id:13
    },
    {
        name:"sushant",
        email:"sushant@gmail.com",
        id:14
    },
    {
        name:"fatima",
        email:"fatima@gmail.com",
        id:15
    },
    {
        name:"pooja",
        email:"pooja@gmail.com",
        id:16
    },
    {
        name:"icon",
        email:"icon@gmail.com",
        id:17
    },
    {
        name:"sandy",
        email:"sabdy@gmail.com",
        id:18
    },
    {
        name:"vicky",
        email:"vicky@gmail.com",
        id:19
    },
    {
        name:"vivekraja",
        email:"vivek@gmail.com",
        id:20
    },
    {
        name:"ghos",
        email:"ghos@gmail.com",
        id:21
    },
    {
        name:"om prakash",
        email:"om@gmail.com",
        id:22
    }
]
export default Robots;